// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// floydWarshallRcpp
NumericMatrix floydWarshallRcpp(NumericMatrix inputMatrix);
RcppExport SEXP _NetAnalyseR_floydWarshallRcpp(SEXP inputMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type inputMatrix(inputMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(floydWarshallRcpp(inputMatrix));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NetAnalyseR_floydWarshallRcpp", (DL_FUNC) &_NetAnalyseR_floydWarshallRcpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_NetAnalyseR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
