# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name floydWarshallRcpp
#' @title Floyd-Warshall Algorithm in R
#' @description This function implements the Floyd-Warshall algorithm using Rcpp for finding the shortest distances
#' between every pair of vertices in a given edge weighted directed Graph. It operates on a matrix representation of the graph.
#' @param inputMatrix A NumericMatrix representing the adjacency matrix of the graph where the element at the ith row
#' and jth column represents the weight of the edge from vertex i to vertex j. If there is no edge between vertex i and vertex j,
#' the value should be 0 for i != j.
#' @return A NumericMatrix where the element at the ith row and jth column represents the shortest distance from vertex i
#' to vertex j in the input graph.
#' @examples
#' # Define the adjacency matrix for a graph
#' W <- matrix(c(0, 2, 1, 4, 2, 0, 3, 5, 1, 3, 0, 6, 4, 5, 6, 0), nrow = 4, byrow = TRUE)
#' # Calculate shortest paths
#' shortestPaths <- floydWarshallRcpp(W)
#' print(shortestPaths)
#' @export
NULL

floydWarshallRcpp <- function(inputMatrix) {
    .Call(`_NetAnalyseR_floydWarshallRcpp`, inputMatrix)
}

